import { SxProps, Theme } from '@mui/material';
import { colors, spacing, shadows, typography, transitions, borderRadius } from './design-tokens';

export const allCardsStyles: Record<string, SxProps<Theme>> = {
  container: {
    backgroundColor: colors.background.dark,
    minHeight: '100vh',
    paddingBottom: spacing.xxxl,
  },
  wrapper: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: { xs: spacing.lg, md: spacing.xxl },
    backgroundColor: colors.neutral.white,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.sm,
  },
  heroBanner: {
    position: 'relative',
    width: '100%',
    height: { xs: '280px', sm: '360px', md: '440px' },
    overflow: 'hidden',
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      display: 'block',
    },
  },
  bannerGradient: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(to bottom, rgba(0,0,0,0.08) 0%, transparent 28%, rgba(0,0,0,0.5) 70%, rgba(0,0,0,0.72) 100%)',
    pointerEvents: 'none',
  },
  bannerNameOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    pointerEvents: 'none',
  },
  bannerHeroName: {
    fontFamily: typography.fontFamily.heading,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize['3xl'], sm: typography.fontSize['4xl'], md: typography.fontSize['5xl'] },
    color: colors.neutral.white,
    lineHeight: typography.lineHeight.tight,
    letterSpacing: '-0.02em',
    textShadow: '0 2px 12px rgba(0,0,0,0.5)',
  },
  bannerAltName: {
    fontFamily: typography.fontFamily.heading,
    fontWeight: typography.fontWeight.normal,
    fontSize: { xs: typography.fontSize.sm, md: typography.fontSize.xl },
    color: 'rgba(255,255,255,0.72)',
    letterSpacing: '0.01em',
    marginTop: spacing.xs,
    textShadow: '0 1px 6px rgba(0,0,0,0.4)',
  },
  stickyRail: {
    position: 'sticky',
    top: 0,
    zIndex: 200,
    backgroundColor: colors.neutral.white,
    borderBottom: `1px solid ${colors.neutral[200]}`,
    boxShadow: '0 2px 6px rgba(0,0,0,0.06)',
  },
  stickyRailInner: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    height: '68px',
    overflowX: 'auto',
    overflowY: 'hidden',
    '&::-webkit-scrollbar': { display: 'none' },
    scrollbarWidth: 'none',
  },
  stickyName: {
    fontFamily: typography.fontFamily.heading,
    fontWeight: typography.fontWeight.semibold,
    fontSize: { xs: typography.fontSize.xl, md: typography.fontSize['2xl'] },
    color: colors.text.primary,
    letterSpacing: '-0.02em',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  stickyCtaLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: `5px 10px`,
    borderRadius: borderRadius.sm,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.medium,
    color: colors.text.secondary,
    border: `1px solid ${colors.neutral[200]}`,
    whiteSpace: 'nowrap',
    transition: transitions.base,
    lineHeight: 1.4,
    '&:hover': {
      color: colors.text.primary,
      borderColor: colors.primary.main,
      backgroundColor: colors.neutral[50],
      textDecoration: 'none',
    },
  },
  controlsSection: {
    backgroundColor: colors.neutral[50],
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    border: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  cardCount: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.display,
  },
  checkbox: {
    color: colors.primary.main,
    '&.Mui-checked': {
      color: colors.primary.main,
    },
  },
  checkboxLabel: {
    fontSize: typography.fontSize.sm,
    fontFamily: typography.fontFamily.primary,
  },
  expandButton: {
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    padding: `${spacing.sm} ${spacing.lg}`,
    borderRadius: borderRadius.lg,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    transition: transitions.base,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
    },
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(auto-fill, minmax(200px, 1fr))',
      sm: 'repeat(auto-fill, minmax(220px, 1fr))',
      md: 'repeat(auto-fill, minmax(240px, 1fr))',
    },
    gap: spacing.lg,
    marginTop: spacing.xl,
  },
  cardImage: {
    width: '100%',
    height: 'auto',
    borderRadius: borderRadius.md,
    boxShadow: shadows.md,
    transition: transitions.base,
    border: `1px solid ${colors.neutral[200]}`,
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: shadows.lg,
    },
  },
  loadingContainer: {
    backgroundColor: colors.background.default,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '50vh',
  },
  loadingSpinner: {
    color: colors.primary.main,
  },
  noCards: {
    textAlign: 'center',
    padding: spacing.xxxl,
    color: colors.text.secondary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
};
