import { SxProps, Theme } from '@mui/material';
import { colors, spacing, shadows, typography, transitions, borderRadius } from './design-tokens';

export const artistStyles: Record<string, SxProps<Theme>> = {
  container: {
    backgroundColor: colors.background.default,
    minHeight: '100vh',
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  contentWrapper: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: { xs: spacing.lg, md: spacing.xxl },
    backgroundColor: colors.neutral.white,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.sm,
  },
  bannerContainer: {
    width: '100%',
    height: { xs: '200px', md: '300px' },
    overflow: 'hidden',
    marginBottom: spacing.xl,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.neutral[100],
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      transition: transitions.base,
    },
  },
  artistName: {
    color: colors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize['3xl'], md: typography.fontSize['4xl'] },
    marginBottom: spacing.lg,
    textAlign: 'center',
    letterSpacing: '-0.02em',
    lineHeight: typography.lineHeight.tight,
    fontFamily: typography.fontFamily.display,
  },
  buttonContainer: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.lg,
    marginBottom: spacing.xxl,
    marginTop: spacing.lg,
  },
  viewCardsLink: {
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    textDecoration: 'none',
    fontWeight: typography.fontWeight.semibold,
    display: 'inline-flex',
    alignItems: 'center',
    padding: `${spacing.md} ${spacing.xl}`,
    borderRadius: borderRadius.lg,
    fontSize: typography.fontSize.base,
    transition: transitions.base,
    boxShadow: shadows.sm,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
      textDecoration: 'none',
    },
  },
  omaLink: {
    backgroundColor: colors.neutral.white,
    color: colors.text.primary,
    textDecoration: 'none',
    fontWeight: typography.fontWeight.semibold,
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.md} ${spacing.xl}`,
    borderRadius: borderRadius.lg,
    fontSize: typography.fontSize.sm,
    border: `1px solid ${colors.neutral[200]}`,
    transition: transitions.base,
    '&:hover': {
      backgroundColor: colors.neutral[50],
      borderColor: colors.primary.main,
    },
    '& .oma-logo': {
      height: '20px',
      width: 'auto',
    },
  },
  artistPage: {
    width: '100%',
  },
  infoSection: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
    gap: spacing.xl,
    alignItems: 'start',
  },
  artistInfo: {
    backgroundColor: colors.neutral.white,
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
    border: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  sectionHeader: {
    color: colors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize['xl'], md: typography.fontSize['2xl'] },
    marginBottom: spacing.md,
    fontFamily: typography.fontFamily.display,
    letterSpacing: '-0.01em',
  },
  infoRow: {
    backgroundColor: colors.neutral[50],
    borderRadius: borderRadius.md,
    padding: spacing.lg,
    border: `1px solid ${colors.neutral[200]}`,
    '& h5': {
      color: colors.text.primary,
      fontWeight: typography.fontWeight.semibold,
      fontSize: typography.fontSize.sm,
      marginBottom: spacing.sm,
      fontFamily: typography.fontFamily.display,
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
    },
    '& p, & a': {
      fontSize: typography.fontSize.base,
      color: colors.text.secondary,
    },
  },
  socialMedia: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  socialIcon: {
    backgroundColor: colors.neutral.white,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    boxShadow: shadows.sm,
    border: `1px solid ${colors.neutral[200]}`,
    transition: transitions.base,
    '& svg': {
      width: '20px',
      height: '20px',
    },
    '&:hover': {
      backgroundColor: colors.neutral[50],
      borderColor: colors.primary.main,
      boxShadow: shadows.md,
    },
  },
  signatureSection: {
    backgroundColor: colors.neutral[50],
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
    border: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.lg,
    '& img': {
      maxWidth: '100%',
      width: '100%',
      borderRadius: borderRadius.md,
      boxShadow: shadows.sm,
      border: `1px solid ${colors.neutral[200]}`,
    },
  },
  loadingContainer: {
    backgroundColor: colors.background.default,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '50vh',
  },
  loadingSpinner: {
    color: colors.primary.main,
  },
  errorMessage: {
    color: colors.accent.red,
    textAlign: 'center',
    padding: spacing.xl,
    backgroundColor: colors.neutral[50],
    borderRadius: borderRadius.lg,
    border: `1px solid ${colors.accent.red}`,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
  serviceLink: {
    backgroundColor: colors.primary.main,
    color: `${colors.neutral.white} !important`,
    textDecoration: 'none',
    fontWeight: typography.fontWeight.semibold,
    padding: `${spacing.md} ${spacing.lg}`,
    borderRadius: borderRadius.lg,
    display: 'inline-block',
    fontSize: typography.fontSize.sm,
    boxShadow: shadows.sm,
    transition: transitions.base,
    width: '100%',
    textAlign: 'center',
    '&:hover': {
      backgroundColor: colors.primary.dark,
      color: `${colors.neutral.white} !important`,
      boxShadow: shadows.md,
      textDecoration: 'none',
    },
    '&:visited': {
      color: `${colors.neutral.white} !important`,
    },
  },
  signingCommentBox: {
    padding: spacing.lg,
    backgroundColor: colors.neutral.white,
    borderLeft: `4px solid ${colors.primary.main}`,
    borderRadius: borderRadius.md,
    '& p': {
      fontStyle: 'italic',
      color: colors.text.secondary,
      fontSize: typography.fontSize.base,
      lineHeight: typography.lineHeight.relaxed,
    },
  },
};
