import { SxProps, Theme } from '@mui/material';
import { colors, themeColors, spacing, shadows, typography, transitions, borderRadius } from './design-tokens';

export const cardBreakdownStyles: Record<string, SxProps<Theme>> = {
  container: {
    backgroundColor: themeColors.background.default,
    minHeight: '100vh',
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  contentWrapper: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: { xs: spacing.lg, md: spacing.xxl },
    backgroundColor: themeColors.neutral.white,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.sm,
  },
  pageTitle: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize['3xl'], md: typography.fontSize['4xl'] },
    marginBottom: spacing.md,
    textAlign: 'center',
    letterSpacing: '-0.02em',
    lineHeight: typography.lineHeight.tight,
    fontFamily: typography.fontFamily.display,
  },
  artistTitle: {
    color: themeColors.text.secondary,
    fontWeight: typography.fontWeight.semibold,
    fontSize: { xs: typography.fontSize.xl, md: typography.fontSize['2xl'] },
    marginBottom: spacing.xxl,
    textAlign: 'center',
    fontFamily: typography.fontFamily.display,
  },
  chartCard: {
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
    border: `1px solid ${themeColors.neutral[200]}`,
    transition: transitions.base,
    '&:hover': {
      boxShadow: shadows.md,
    },
  },
  chartTitle: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize.lg, md: typography.fontSize.xl },
    marginBottom: spacing.lg,
    fontFamily: typography.fontFamily.display,
    letterSpacing: '-0.01em',
  },
  gridContainer: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' },
    gap: spacing.xl,
    marginBottom: spacing.xl,
  },
  loadingContainer: {
    backgroundColor: themeColors.background.default,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
  },
  loadingSpinner: {
    color: themeColors.primary.main,
  },
  errorMessage: {
    color: colors.accent.red,
    textAlign: 'center',
    padding: spacing.xl,
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.lg,
    border: `1px solid ${colors.accent.red}`,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
  table: {
    minWidth: '100%',
    background: themeColors.neutral.white,
    fontSize: { xs: typography.fontSize.xs, sm: typography.fontSize.sm, md: typography.fontSize.base },
    borderCollapse: 'collapse',
    border: `1px solid ${themeColors.neutral[200]}`,
    borderRadius: borderRadius.md,
    overflow: 'hidden',
  },
  tableHead: {
    backgroundColor: themeColors.neutral[100],
  },
  tableHeaderCell: {
    padding: { xs: spacing.md, md: spacing.lg },
    textAlign: 'left',
    fontWeight: typography.fontWeight.semibold,
    borderBottom: `1px solid ${themeColors.neutral[300]}`,
    borderRight: `1px solid ${themeColors.neutral[200]}`,
    color: themeColors.text.primary,
  },
  tableRow: {
    '&:nth-of-type(even)': {
      backgroundColor: themeColors.neutral[50],
    },
  },
  tableCell: {
    padding: { xs: spacing.md, md: spacing.lg },
    borderBottom: `1px solid ${themeColors.neutral[200]}`,
    borderRight: `1px solid ${themeColors.neutral[200]}`,
    color: themeColors.text.secondary,
  },
  tableCellName: {
    padding: { xs: spacing.md, md: spacing.lg },
    fontWeight: typography.fontWeight.medium,
    color: themeColors.primary.main,
    borderBottom: `1px solid ${themeColors.neutral[200]}`,
    borderRight: `1px solid ${themeColors.neutral[200]}`,
  },
  tableCellOracleText: {
    padding: { xs: spacing.md, md: spacing.lg },
    fontSize: { xs: typography.fontSize.xs, sm: typography.fontSize.sm },
    borderBottom: `1px solid ${themeColors.neutral[200]}`,
    maxWidth: { xs: '300px', lg: '400px' },
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: themeColors.text.secondary,
  },
  statsCard: {
    backgroundColor: themeColors.neutral[50],
    padding: { xs: spacing.lg, md: spacing.xl },
    borderRadius: borderRadius.md,
    border: `1px solid ${themeColors.neutral[200]}`,
  },
  statsTitle: {
    fontWeight: typography.fontWeight.semibold,
    fontSize: { xs: typography.fontSize.base, md: typography.fontSize.lg },
    marginBottom: { xs: spacing.md, md: spacing.lg },
    color: themeColors.text.primary,
  },
  statsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: { xs: spacing.md, md: spacing.lg },
    fontSize: { xs: typography.fontSize.sm, md: typography.fontSize.base },
  },
  statsItem: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  statsLabel: {
    fontWeight: typography.fontWeight.medium,
    color: themeColors.text.secondary,
  },
  statsValue: {
    color: themeColors.text.primary,
  },
};
