import { SxProps, Theme } from '@mui/material';
import { colors, themeColors, spacing, shadows, typography, transitions, borderRadius } from './design-tokens';

// Shared styles for content-heavy pages (Signing Services, Calendar, etc.)
export const contentPageStyles: Record<string, SxProps<Theme>> = {
  container: {
    backgroundColor: themeColors.background.default,
    minHeight: '100vh',
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  wrapper: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: { xs: spacing.lg, md: spacing.xxl },
    backgroundColor: themeColors.background.paper,
  },
  pageTitle: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize['3xl'], md: typography.fontSize['4xl'] },
    marginBottom: spacing.xxl,
    textAlign: 'center',
    letterSpacing: { xs: '-0.01em', md: '-0.022em' },
    lineHeight: typography.lineHeight.tight,
    fontFamily: typography.fontFamily.heading,
  },
  sectionTitle: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize.xl, md: typography.fontSize['2xl'] },
    marginTop: spacing.xxl,
    marginBottom: spacing.lg,
    fontFamily: typography.fontFamily.heading,
  },
  paragraph: {
    color: themeColors.text.secondary,
    fontSize: typography.fontSize.base,
    lineHeight: typography.lineHeight.relaxed,
    marginBottom: spacing.lg,
    fontFamily: typography.fontFamily.primary,
  },
  card: {
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    border: `1px solid ${themeColors.neutral[200]}`,
  },
  cardTitle: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.lg,
    marginBottom: spacing.md,
    fontFamily: typography.fontFamily.display,
  },
  cardText: {
    color: themeColors.text.secondary,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.lineHeight.relaxed,
    marginBottom: spacing.sm,
  },
  link: {
    color: themeColors.primary.main,
    textDecoration: 'none',
    fontWeight: typography.fontWeight.medium,
    transition: transitions.fast,
    '&:hover': {
      color: colors.primary.dark,
      textDecoration: 'underline',
    },
  },
  button: {
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    padding: `${spacing.md} ${spacing.xl}`,
    borderRadius: borderRadius.sm,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    transition: transitions.base,
    textDecoration: 'none',
    display: 'inline-block',
    boxShadow: shadows.sm,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
      textDecoration: 'none',
    },
  },
  divider: {
    borderColor: themeColors.neutral[200],
    marginTop: spacing.xl,
    marginBottom: spacing.xl,
  },
  serviceCard: {
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    padding: spacing.xl,
    marginBottom: spacing.xl,
    border: `1px solid ${themeColors.neutral[200]}`,
    transition: transitions.base,
    '&:hover': {
      boxShadow: shadows.md,
    },
  },
  serviceName: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize.xl, md: typography.fontSize['2xl'] },
    marginBottom: spacing.lg,
    textAlign: 'center',
    fontFamily: typography.fontFamily.heading,
  },
  serviceStats: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    gap: spacing.lg,
    marginBottom: spacing.lg,
  },
  statItem: {
    textAlign: 'center',
    flex: 1,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: themeColors.neutral.white,
    border: `1px solid ${themeColors.neutral[200]}`,
  },
  statLabel: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.xs,
    fontFamily: typography.fontFamily.display,
  },
  statValue: {
    color: themeColors.text.secondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  serviceInfo: {
    backgroundColor: themeColors.neutral.white,
    borderRadius: borderRadius.md,
    padding: spacing.lg,
    border: `1px solid ${themeColors.neutral[200]}`,
  },
  eventsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
    marginTop: spacing.lg,
  },
  eventCard: {
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    padding: { xs: spacing.md, md: spacing.lg },
    border: `1px solid ${themeColors.neutral[200]}`,
    transition: transitions.base,
    '&:hover': {
      boxShadow: shadows.md,
    },
  },
  eventTitle: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize.lg, md: typography.fontSize.xl },
    fontFamily: typography.fontFamily.heading,
  },
  infoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.lg,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  infoItem: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.xs,
    color: themeColors.text.secondary,
    fontWeight: typography.fontWeight.medium,
    fontSize: typography.fontSize.sm,
    '& .MuiSvgIcon-root': {
      color: themeColors.primary.main,
      fontSize: typography.fontSize.base,
    },
  },
  artistsContainer: {
    marginTop: spacing.lg,
    backgroundColor: themeColors.neutral.white,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    border: `1px solid ${themeColors.neutral[200]}`,
  },
  artistsHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    cursor: 'pointer',
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    transition: transitions.fast,
    '&:hover': {
      backgroundColor: themeColors.neutral[100],
    },
  },
  artistsHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    color: themeColors.text.secondary,
  },
  artistsHeaderText: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.sm,
    fontFamily: typography.fontFamily.display,
  },
  expandIcon: {
    color: themeColors.primary.main,
    transition: transitions.base,
  },
  artistsGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
    justifyContent: 'flex-start',
  },
  artistChip: {
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    textDecoration: 'none',
    padding: `${spacing.xs} ${spacing.md}`,
    borderRadius: borderRadius.sm,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    display: 'inline-block',
    border: `1px solid ${colors.primary.dark}`,
    transition: transitions.fast,
    fontFamily: typography.fontFamily.primary,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      textDecoration: 'none',
    },
  },
  loadingContainer: {
    padding: spacing.xl,
    display: 'flex',
    justifyContent: 'center',
    '& .MuiLinearProgress-root': {
      width: '100%',
      maxWidth: 600,
      borderRadius: borderRadius.sm,
      backgroundColor: themeColors.neutral[200],
      '& .MuiLinearProgress-bar': {
        backgroundColor: themeColors.primary.main,
      },
    },
  },
  errorMessage: {
    color: colors.accent.red,
    textAlign: 'center',
    padding: spacing.xl,
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.accent.red}`,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.medium,
    margin: spacing.md,
  },
  noEventsMessage: {
    textAlign: 'center',
    padding: spacing.xl,
    color: themeColors.text.secondary,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.medium,
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    border: `1px solid ${themeColors.neutral[200]}`,
    margin: spacing.md,
  },
  contentContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.xl,
  },
  flavorCardContainer: {
    maxWidth: 800,
    width: '100%',
    padding: { xs: spacing.lg, md: spacing.xxl },
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    border: `1px solid ${themeColors.neutral[200]}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.md,
    transition: transitions.base,
    '&:hover': {
      boxShadow: shadows.md,
    },
  },
  cardName: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize.xl, md: typography.fontSize['2xl'] },
    textAlign: 'center',
    fontFamily: typography.fontFamily.heading,
    marginBottom: 0,
  },
  artistByline: {
    fontStyle: 'italic',
    color: themeColors.text.secondary,
    mb: 0,
    mt: 0,
    textAlign: 'center',
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    maxWidth: { xs: '100%', md: 600 },
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    boxShadow: shadows.md,
    marginBottom: spacing.md,
    border: `1px solid ${themeColors.neutral[200]}`,
    '& img': {
      width: '100%',
      height: 'auto',
      objectFit: 'cover',
      display: 'block',
    },
  },
  flavorText: {
    fontStyle: 'italic',
    fontSize: { xs: typography.fontSize.base, md: typography.fontSize.lg },
    color: themeColors.text.secondary,
    textAlign: 'center',
    lineHeight: typography.lineHeight.relaxed,
    padding: spacing.lg,
    backgroundColor: themeColors.neutral.white,
    borderRadius: borderRadius.md,
    border: `1px solid ${themeColors.neutral[200]}`,
    borderLeft: `4px solid ${colors.primary.main}`,
    maxWidth: '90%',
    fontFamily: typography.fontFamily.primary,
    fontWeight: typography.fontWeight.normal,
  },
  reloadButton: {
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    paddingX: spacing.xxl,
    paddingY: spacing.md,
    fontWeight: typography.fontWeight.semibold,
    borderRadius: borderRadius.sm,
    fontSize: typography.fontSize.base,
    fontFamily: typography.fontFamily.primary,
    border: `1px solid ${colors.primary.dark}`,
    transition: transitions.base,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
    },
    '&:disabled': {
      backgroundColor: colors.neutral[300],
      color: colors.neutral[500],
    },
  },
  flavorLoadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '50vh',
    '& .MuiCircularProgress-root': {
      color: themeColors.primary.main,
    },
  },
  errorAlert: {
    marginBottom: spacing.lg,
    width: '100%',
    maxWidth: 800,
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.accent.red}`,
    '& .MuiAlert-message': {
      fontSize: typography.fontSize.base,
      fontWeight: typography.fontWeight.medium,
      fontFamily: typography.fontFamily.primary,
    },
  },
  contactInfo: {
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    padding: spacing.xxl,
    marginTop: spacing.xxl,
    border: `1px solid ${themeColors.neutral[200]}`,
    transition: transitions.base,
    '&:hover': {
      boxShadow: shadows.md,
    },
  },
  contactTitle: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.bold,
    marginBottom: spacing.lg,
    fontSize: typography.fontSize.xl,
    fontFamily: typography.fontFamily.heading,
  },
  contactMethod: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.lg,
    padding: spacing.md,
    backgroundColor: themeColors.neutral.white,
    borderRadius: borderRadius.md,
    border: `1px solid ${themeColors.neutral[200]}`,
    transition: transitions.fast,
    '&:hover': {
      backgroundColor: themeColors.neutral[50],
      boxShadow: shadows.sm,
    },
  },
  contactIcon: {
    color: themeColors.primary.main,
    fontSize: typography.fontSize.xl,
  },
  contactLink: {
    color: themeColors.primary.main,
    fontWeight: typography.fontWeight.semibold,
    textDecoration: 'none',
    fontSize: typography.fontSize.base,
    fontFamily: typography.fontFamily.primary,
    transition: transitions.fast,
    '&:hover': {
      color: colors.primary.dark,
      textDecoration: 'none',
    },
  },
  responseTime: {
    marginTop: spacing.lg,
    color: themeColors.text.secondary,
    fontSize: typography.fontSize.sm,
    fontStyle: 'italic',
    textAlign: 'center',
    fontFamily: typography.fontFamily.primary,
    backgroundColor: themeColors.neutral.white,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    border: `1px solid ${themeColors.neutral[200]}`,
  },
};
