import { SxProps, Theme } from '@mui/material';
import { colors, spacing, typography, transitions, borderRadius } from './design-tokens';

export const footerStyles: Record<string, SxProps<Theme>> = {
  footerContainer: {
    backgroundColor: colors.neutral.white,
    borderTop: `1px solid ${colors.neutral[200]}`,
    padding: { xs: spacing.xl, md: spacing.xxl },
    marginTop: 'auto',
  },
  footerContent: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: '1400px',
    margin: '0 auto',
    gap: spacing.lg,
  },
  footerText: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    fontFamily: typography.fontFamily.primary,
    textAlign: 'center',
  },
  footerLinks: {
    display: 'flex',
    gap: spacing.lg,
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  badgeContainer: {
    position: { xs: 'relative', md: 'absolute' },
    bottom: { md: 0 },
    right: { md: 0 },
    marginTop: { xs: spacing.md, md: 0 },
  },
  link: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    fontFamily: typography.fontFamily.primary,
    textDecoration: 'none',
    padding: `${spacing.sm} ${spacing.md}`,
    borderRadius: borderRadius.md,
    transition: transitions.base,
    '&:hover': {
      color: colors.primary.main,
      backgroundColor: colors.neutral[50],
      textDecoration: 'none',
    },
  },
  iconLink: {
    color: colors.text.secondary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    transition: transitions.base,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '&:hover': {
      color: colors.primary.main,
      backgroundColor: colors.neutral[50],
    },
  },
  supportBanner: {
    backgroundColor: colors.neutral[50],
    borderTop: `1px solid ${colors.neutral[200]}`,
    padding: { xs: spacing.xl, md: spacing.xxl },
    textAlign: 'center',
  },
  supportBannerInner: {
    maxWidth: '680px',
    margin: '0 auto',
  },
  supportHeading: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.primary,
    marginBottom: spacing.md,
  },
  supportBody: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.sm,
    fontFamily: typography.fontFamily.primary,
    lineHeight: typography.lineHeight.relaxed,
    marginBottom: spacing.lg,
  },
  supportActions: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.lg,
    marginBottom: spacing.md,
  },
  supportSubtext: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.sm,
    fontFamily: typography.fontFamily.primary,
    lineHeight: typography.lineHeight.relaxed,
  },
};
