import { SxProps, Theme } from '@mui/material';
import { colors, spacing, shadows, typography, transitions, borderRadius } from './design-tokens';

export type Styles = {
    [key:string]: SxProps;
};

export const homepageStyles: Record<string, SxProps<Theme>> = {
  container: {
    backgroundColor: colors.background.default,
    minHeight: '100vh',
    paddingTop: { xs: spacing.sm, md: spacing.xs },
    paddingBottom: spacing.xxxl,
  },
  wrapper: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: { xs: spacing.md, md: spacing.lg },
  },
  headerSection: {
    textAlign: 'center',
    marginBottom: { xs: spacing.md, md: spacing.sm },
    maxWidth: '900px',
    margin: '0 auto',
    paddingBottom: 0,
  },
  headerText: {
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize['3xl'], md: typography.fontSize['4xl'], lg: typography.fontSize['5xl'] },
    marginBottom: { xs: spacing.xs, md: 0 },
    color: colors.text.primary,
    fontFamily: typography.fontFamily.display,
    letterSpacing: '-0.02em',
    lineHeight: typography.lineHeight.tight,
  },
  description: {
    fontSize: { xs: typography.fontSize.base, md: typography.fontSize.lg },
    color: colors.text.secondary,
    lineHeight: { xs: typography.lineHeight.relaxed, md: typography.lineHeight.normal },
    marginBottom: { xs: spacing.xs, md: 0 },
    fontFamily: typography.fontFamily.primary,
    maxWidth: '800px',
    margin: { xs: `${spacing.xs} auto`, md: `0 auto` },
  },
  descriptionList: {
    fontSize: { xs: typography.fontSize.sm, md: typography.fontSize.base },
    color: colors.text.secondary,
    lineHeight: { xs: typography.lineHeight.relaxed, md: typography.lineHeight.normal },
    marginBottom: 0,
    maxWidth: '800px',
    margin: `0 auto`,
    '& b': {
      color: colors.text.primary,
      fontWeight: typography.fontWeight.semibold,
    },
  },
  count: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    padding: `${spacing.sm} ${spacing.xl}`,
    borderRadius: borderRadius.full,
    textAlign: 'center',
    margin: { xs: `${spacing.lg} auto ${spacing.sm}`, md: `${spacing.md} auto ${spacing.xs}` },
    boxShadow: shadows.sm,
    fontFamily: typography.fontFamily.display,
    transition: transitions.base,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
    },
  },
  filtersSection: {
    backgroundColor: colors.neutral.white,
    borderRadius: borderRadius.xl,
    padding: { xs: spacing.lg, md: spacing.xl },
    marginBottom: spacing.xl,
    marginTop: spacing.xl,
    border: `1px solid ${colors.neutral[200]}`,
    boxShadow: shadows.sm,
  },
  filtersGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '2fr 1.5fr 1.5fr' },
    gap: spacing.lg,
    alignItems: 'start',
  },
  searchContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  randomButton: {
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    fontWeight: typography.fontWeight.semibold,
    borderRadius: borderRadius.lg,
    padding: `${spacing.sm} ${spacing.lg}`,
    textTransform: 'none',
    fontSize: typography.fontSize.base,
    transition: transitions.base,
    boxShadow: shadows.sm,
    fontFamily: typography.fontFamily.display,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
      transform: 'translateY(-1px)',
    },
  },
  textField: {
    width: '100%',
    '& .MuiOutlinedInput-root': {
      borderRadius: borderRadius.lg,
      backgroundColor: colors.neutral.white,
      transition: transitions.base,
      '&:hover fieldset': {
        borderColor: colors.primary.main,
      },
      '&.Mui-focused fieldset': {
        borderColor: colors.primary.main,
        borderWidth: '2px',
      },
    },
    '& .MuiInputLabel-root': {
      '&.Mui-focused': {
        color: colors.primary.main,
      },
    },
  },
  locationSelect: {
    width: '100%',
    '& .MuiOutlinedInput-root': {
      borderRadius: borderRadius.lg,
      backgroundColor: colors.neutral.white,
      transition: transitions.base,
      '&:hover .MuiOutlinedInput-notchedOutline': {
        borderColor: colors.primary.main,
      },
      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
        borderColor: colors.primary.main,
        borderWidth: '2px',
      },
    },
    '& .MuiInputLabel-root': {
      '&.Mui-focused': {
        color: colors.primary.main,
      },
    },
  },
  checkboxContainer: {
    backgroundColor: colors.neutral[50],
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    border: `1px solid ${colors.neutral[200]}`,
  },
  checkboxesContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
  },
  signingAgentLabel: {
    color: colors.text.primary,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    fontFamily: typography.fontFamily.display,
  },
  checkbox: {
    color: colors.primary.main,
    '&.Mui-checked': {
      color: colors.primary.main,
    },
  },
  alphabetBar: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: spacing.xs,
    marginTop: spacing.xl,
  },
  alphabetLink: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: { xs: '32px', md: '36px' },
    height: { xs: '32px', md: '36px' },
    padding: `${spacing.xs} ${spacing.sm}`,
    border: `1px solid ${colors.neutral[200]}`,
    borderRadius: borderRadius.md,
    backgroundColor: colors.neutral.white,
    color: colors.text.primary,
    fontSize: { xs: typography.fontSize.xs, md: typography.fontSize.sm },
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.display,
    cursor: 'pointer',
    transition: transitions.fast,
    '&:hover': {
      backgroundColor: colors.primary.main,
      color: colors.neutral.white,
      borderColor: colors.primary.main,
    },
  },
  alphabetLinkActive: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: { xs: '32px', md: '36px' },
    height: { xs: '32px', md: '36px' },
    padding: `${spacing.xs} ${spacing.sm}`,
    borderRadius: borderRadius.md,
    fontSize: { xs: typography.fontSize.xs, md: typography.fontSize.sm },
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.display,
    cursor: 'pointer',
    transition: transitions.fast,
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    border: `1px solid ${colors.primary.main}`,
    boxShadow: shadows.sm,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      color: colors.neutral.white,
      borderColor: colors.primary.dark,
    },
  },
  artistsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(3, 1fr)',
      lg: 'repeat(4, 1fr)',
      xl: 'repeat(5, 1fr)'
    },
    gap: { xs: spacing.lg, md: spacing.xl },
    marginTop: spacing.xl,
  },
  loadingContainer: {
    backgroundColor: colors.background.default,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
  },
  loadingSpinner: {
    color: colors.primary.main,
  },
  errorMessage: {
    color: colors.accent.red,
    textAlign: 'center',
    padding: spacing.xl,
    backgroundColor: colors.neutral[50],
    borderRadius: borderRadius.lg,
    border: `1px solid ${colors.accent.red}`,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
  noResults: {
    textAlign: 'center',
    padding: spacing.xxxl,
    color: colors.text.secondary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
    gridColumn: '1 / -1',
  },
};
