import { SxProps, Theme } from '@mui/material';
import { colors, themeColors, spacing, shadows, typography, transitions, borderRadius } from './design-tokens';

export type Styles = {
    [key:string]: SxProps;
};

export const homepageStyles: Record<string, SxProps<Theme>> = {
  container: {
    backgroundColor: themeColors.background.default,
    minHeight: '100vh',
    paddingTop: { xs: spacing.sm, md: spacing.xs },
    paddingBottom: spacing.xxxl,
  },
  wrapper: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: { xs: spacing.md, md: spacing.lg },
  },
  headerSection: {
    textAlign: 'center',
    marginBottom: { xs: spacing.md, md: spacing.sm },
    maxWidth: '900px',
    margin: '0 auto',
    paddingBottom: 0,
  },
  headerText: {
    fontWeight: typography.fontWeight.bold,
    fontSize: { xs: typography.fontSize['3xl'], md: typography.fontSize['4xl'], lg: typography.fontSize['5xl'] },
    marginBottom: { xs: spacing.xs, md: 0 },
    color: themeColors.text.primary,
    fontFamily: typography.fontFamily.heading,
    letterSpacing: '-0.01em',
    lineHeight: typography.lineHeight.tight,
  },
  description: {
    fontSize: { xs: typography.fontSize.base, md: typography.fontSize.lg },
    color: themeColors.text.secondary,
    lineHeight: { xs: typography.lineHeight.relaxed, md: typography.lineHeight.normal },
    marginBottom: { xs: spacing.xs, md: 0 },
    fontFamily: typography.fontFamily.primary,
    maxWidth: '800px',
    margin: { xs: `${spacing.xs} auto`, md: `0 auto` },
  },
  descriptionList: {
    fontSize: { xs: typography.fontSize.sm, md: typography.fontSize.base },
    color: themeColors.text.secondary,
    lineHeight: { xs: typography.lineHeight.relaxed, md: typography.lineHeight.normal },
    marginBottom: 0,
    maxWidth: '800px',
    margin: `0 auto`,
    '& b': {
      color: themeColors.text.primary,
      fontWeight: typography.fontWeight.semibold,
    },
  },
  count: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    padding: `${spacing.sm} ${spacing.xl}`,
    borderRadius: borderRadius.full,
    textAlign: 'center',
    margin: { xs: `${spacing.lg} auto ${spacing.sm}`, md: `${spacing.md} auto ${spacing.xs}` },
    boxShadow: shadows.sm,
    fontFamily: typography.fontFamily.display,
    transition: transitions.base,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
    },
  },
  filtersSection: {
    paddingTop: { xs: spacing.lg, md: spacing.xl },
    paddingBottom: { xs: spacing.lg, md: spacing.xl },
    marginBottom: spacing.xl,
    marginTop: spacing.xl,
    borderTop: `1px solid ${themeColors.neutral[200]}`,
    borderBottom: `1px solid ${themeColors.neutral[200]}`,
  },
  filtersGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1fr 1fr' },
    gap: spacing.lg,
    alignItems: 'start',
  },
  searchContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  randomButton: {
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    fontWeight: typography.fontWeight.semibold,
    borderRadius: borderRadius.sm,
    padding: `${spacing.sm} ${spacing.lg}`,
    textTransform: 'none',
    fontSize: typography.fontSize.base,
    transition: transitions.base,
    boxShadow: shadows.sm,
    fontFamily: typography.fontFamily.display,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      boxShadow: shadows.md,
      transform: 'translateY(-1px)',
    },
  },
  textField: {
    width: '100%',
    '& .MuiOutlinedInput-root': {
      borderRadius: borderRadius.md,
      backgroundColor: themeColors.neutral.white,
      color: themeColors.text.primary,
      transition: transitions.base,
      '& fieldset': {
        borderColor: themeColors.neutral[300],
      },
      '&:hover fieldset': {
        borderColor: themeColors.primary.main,
      },
      '&.Mui-focused fieldset': {
        borderColor: themeColors.primary.main,
        borderWidth: '2px',
      },
    },
    '& .MuiInputLabel-root': {
      color: themeColors.text.secondary,
      '&.Mui-focused': {
        color: themeColors.primary.main,
      },
    },
    '& .MuiInputAdornment-root': {
      color: themeColors.text.secondary,
    },
  },
  locationSelect: {
    width: '100%',
    '& .MuiOutlinedInput-root': {
      borderRadius: borderRadius.md,
      backgroundColor: themeColors.neutral.white,
      color: themeColors.text.primary,
      transition: transitions.base,
      '& .MuiOutlinedInput-notchedOutline': {
        borderColor: themeColors.neutral[300],
      },
      '&:hover .MuiOutlinedInput-notchedOutline': {
        borderColor: themeColors.primary.main,
      },
      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
        borderColor: themeColors.primary.main,
        borderWidth: '2px',
      },
    },
    '& .MuiInputLabel-root': {
      color: themeColors.text.secondary,
      '&.Mui-focused': {
        color: themeColors.primary.main,
      },
    },
    '& .MuiSvgIcon-root': {
      color: themeColors.text.secondary,
    },
  },
  checkboxContainer: {
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    padding: spacing.md,
    border: `1px solid ${themeColors.neutral[200]}`,
  },
  checkboxesContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    '& .MuiFormControlLabel-label': {
      color: themeColors.text.primary,
    },
  },
  signingAgentLabel: {
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    fontFamily: typography.fontFamily.display,
  },
  checkbox: {
    color: themeColors.primary.main,
    '&.Mui-checked': {
      color: themeColors.primary.main,
    },
  },
  alphabetBar: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: spacing.xs,
    marginTop: spacing.xl,
  },
  alphabetLink: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: { xs: '32px', md: '36px' },
    height: { xs: '32px', md: '36px' },
    padding: `${spacing.xs} ${spacing.sm}`,
    border: `1px solid ${themeColors.neutral[200]}`,
    borderRadius: borderRadius.md,
    backgroundColor: themeColors.neutral.white,
    color: themeColors.text.primary,
    fontSize: { xs: typography.fontSize.xs, md: typography.fontSize.sm },
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.display,
    cursor: 'pointer',
    transition: transitions.fast,
    '&:hover': {
      backgroundColor: colors.primary.main,
      color: colors.neutral.white,
      borderColor: colors.primary.main,
    },
  },
  alphabetLinkActive: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: { xs: '32px', md: '36px' },
    height: { xs: '32px', md: '36px' },
    padding: `${spacing.xs} ${spacing.sm}`,
    borderRadius: borderRadius.md,
    fontSize: { xs: typography.fontSize.xs, md: typography.fontSize.sm },
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.display,
    cursor: 'pointer',
    transition: transitions.fast,
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    border: `1px solid ${colors.primary.main}`,
    boxShadow: shadows.sm,
    '&:hover': {
      backgroundColor: colors.primary.dark,
      color: colors.neutral.white,
      borderColor: colors.primary.dark,
    },
  },
  artistsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, 1fr)',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(3, 1fr)',
      lg: 'repeat(4, 1fr)',
      xl: 'repeat(5, 1fr)'
    },
    gap: { xs: spacing.sm, sm: spacing.md, md: spacing.xl },
    marginTop: spacing.xl,
  },
  artistsGridCompact: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(3, 1fr)',
      sm: 'repeat(4, 1fr)',
      md: 'repeat(6, 1fr)',
      lg: 'repeat(7, 1fr)',
      xl: 'repeat(8, 1fr)',
    },
    gap: { xs: spacing.xs, sm: spacing.sm, md: spacing.md },
    marginTop: spacing.xl,
  },
  artistsGridGallery: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(1, 1fr)',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(2, 1fr)',
      lg: 'repeat(3, 1fr)',
      xl: 'repeat(4, 1fr)',
    },
    gap: { xs: spacing.sm, sm: spacing.md, md: spacing.lg },
    marginTop: spacing.xl,
  },
  loadingContainer: {
    backgroundColor: themeColors.background.default,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
  },
  loadingSpinner: {
    color: themeColors.primary.main,
  },
  errorMessage: {
    color: colors.accent.red,
    textAlign: 'center',
    padding: spacing.xl,
    backgroundColor: themeColors.neutral[50],
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.accent.red}`,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
  scrollToTop: {
    position: 'fixed',
    bottom: spacing.xl,
    right: '96px',
    backgroundColor: colors.primary.main,
    color: colors.neutral.white,
    boxShadow: shadows.lg,
    zIndex: 999,
    '&:hover': {
      backgroundColor: colors.primary.dark,
    },
  },
  noResults: {
    textAlign: 'center',
    padding: spacing.xxxl,
    color: themeColors.text.secondary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
    gridColumn: '1 / -1',
  },
  filterStrip: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 1,
    py: 1.5,
    px: 1,
    borderRadius: borderRadius.md,
    mb: 1,
    marginTop: '20px',
  },
  filterStripActive: {
    backgroundColor: themeColors.neutral[100],
  },
  filterStripCount: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: themeColors.text.primary,
    mr: 1,
  },
  filterChip: {
    backgroundColor: colors.primary.main,
    color: colors.primary.contrast,
    fontSize: typography.fontSize.xs,
    height: '26px',
    '& .MuiChip-deleteIcon': {
      color: 'rgba(255,255,255,0.7)',
      fontSize: '1rem',
      '&:hover': { color: colors.primary.contrast },
    },
  },
  clearAllButton: {
    fontSize: typography.fontSize.xs,
    textTransform: 'none',
    color: themeColors.text.secondary,
    ml: 1,
    '&:hover': {
      backgroundColor: 'rgba(0,0,0,0.04)',
      color: themeColors.text.primary,
    },
  },
  listSubheader: {
    backgroundColor: themeColors.neutral[100],
    color: themeColors.text.primary,
    fontWeight: typography.fontWeight.semibold,
    lineHeight: '32px',
  },
  filterChipAmber: {
    backgroundColor: colors.accent.orange,
    color: colors.neutral.white,
    fontSize: typography.fontSize.xs,
    height: '26px',
    '& .MuiChip-deleteIcon': {
      color: 'rgba(255,255,255,0.7)',
      fontSize: '1rem',
      '&:hover': { color: colors.neutral.white },
    },
  },
  mobileFilterRow: {
    display: { xs: 'flex', sm: 'none' },
    gap: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    marginTop: spacing.md,
    borderTop: `1px solid ${themeColors.neutral[200]}`,
    borderBottom: `1px solid ${themeColors.neutral[200]}`,
  },
  mobileFilterButton: {
    flex: 2,
    textTransform: 'none',
    fontFamily: typography.fontFamily.display,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.sm,
    borderColor: themeColors.neutral[300],
    color: themeColors.text.primary,
    '&:hover': {
      borderColor: themeColors.primary.main,
    },
  },
  mobileFilterButtonActive: {
    flex: 2,
    textTransform: 'none',
    fontFamily: typography.fontFamily.display,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.sm,
    backgroundColor: colors.primary.main,
    color: colors.primary.contrast,
    '&:hover': {
      backgroundColor: colors.primary.dark,
    },
  },
  filterSheetPaper: {
    borderRadius: `${borderRadius.xl} ${borderRadius.xl} 0 0`,
    maxHeight: '85vh',
    backgroundColor: themeColors.background.default,
  },
  filterSheetHandle: {
    width: '40px',
    height: '4px',
    borderRadius: borderRadius.full,
    backgroundColor: themeColors.neutral[300],
    mx: 'auto',
  },
  filterSheetHeader: {
    px: spacing.md,
    pt: spacing.sm,
    pb: spacing.md,
    borderBottom: `1px solid ${themeColors.neutral[200]}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterSheetTitle: {
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.base,
    fontFamily: typography.fontFamily.display,
    color: themeColors.text.primary,
  },
  filterSheetContent: {
    px: spacing.md,
    pt: spacing.md,
    pb: spacing.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  filterSheetActions: {
    px: spacing.md,
    pt: spacing.md,
    pb: spacing.xl,
  },
};
