import { Theme } from '@mui/material';
import { SystemStyleObject } from '@mui/system';
import { typography, vault, vaultEffects, vaultLayout, vaultMedia, vaultRadii } from './design-tokens';

const focusRing = {
  '&:focus-visible': { outline: `2px solid ${vault.accent}`, outlineOffset: 2 },
};

const notice = {
  marginBottom: '24px',
  padding: '14px 18px',
  borderRadius: vaultRadii.card,
  fontSize: 14,
  lineHeight: 1.55,
};

export const scanEventArtistsStyles: Record<string, SystemStyleObject<Theme>> = {
  page: {
    minHeight: '100vh',
    color: vault.fg,
    background: `${vaultEffects.heroGlowLeft}, ${vault.bg}`,
    backgroundRepeat: 'no-repeat',
    backgroundSize: '100% 420px, auto',
  },
  inner: {
    maxWidth: 860,
    mx: 'auto',
    padding: `64px ${vaultLayout.gutter} 72px`,
    [vaultMedia.mobile]: { padding: `40px ${vaultLayout.gutterMobile} 48px` },
  },

  // ─── Header ────────────────────────────────────────────────────────────────
  eyebrow: {
    marginBottom: '16px',
    [vaultMedia.mobile]: { marginBottom: '12px' },
  },
  title: {
    margin: 0,
    fontSize: 56,
    lineHeight: 1,
    fontWeight: 600,
    letterSpacing: '-0.035em',
    color: vault.fg,
    [vaultMedia.mobile]: { fontSize: 40 },
  },
  intro: {
    margin: '16px 0 32px',
    maxWidth: 720,
    fontSize: 15,
    lineHeight: 1.6,
    color: vault.muted,
    [vaultMedia.mobile]: { fontSize: 14, marginBottom: '24px' },
  },

  // ─── URL bar ───────────────────────────────────────────────────────────────
  scanBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    height: 60,
    padding: '0 8px 0 18px',
    marginBottom: '24px',
    borderRadius: vaultRadii.search,
    backgroundColor: vault.surface,
    border: `1px solid ${vault.lineStrong}`,
    color: vault.faint,
    transition: `border-color ${vaultEffects.transition}, box-shadow ${vaultEffects.transition}`,
    '&:focus-within': { borderColor: vault.accent, boxShadow: vaultEffects.searchShadow },
    [vaultMedia.mobile]: { height: 52, borderRadius: '13px', padding: '0 6px 0 14px' },
  },
  scanInput: {
    flex: 1,
    minWidth: 0,
    height: '100%',
    border: 'none',
    outline: 'none',
    background: 'transparent',
    color: vault.fg,
    fontFamily: 'inherit',
    fontSize: 16,
    '&::placeholder': { color: vault.faint },
    '&:disabled': { color: vault.muted },
  },
  scanButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    flex: 'none',
    height: 44,
    padding: '0 18px',
    border: 'none',
    borderRadius: '9px',
    backgroundColor: vault.accent,
    color: vault.onAccent,
    fontFamily: 'inherit',
    fontSize: 14,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    transition: `box-shadow ${vaultEffects.transition}`,
    '&:hover:not(:disabled)': { boxShadow: `0 0 0 4px ${vault.glow}` },
    '&:disabled': { cursor: 'default', backgroundColor: vault.chipStrong, color: vault.faint },
    ...focusRing,
    [vaultMedia.mobile]: { height: 40, padding: '0 14px' },
  },

  // ─── Status + notices ──────────────────────────────────────────────────────
  scanning: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '24px',
    fontSize: 14,
    color: vault.muted,
  },
  pulse: {
    '@keyframes scanPulse': { '0%, 100%': { opacity: 1 }, '50%': { opacity: 0.3 } },
    display: 'flex',
    animation: 'scanPulse 1.4s ease-in-out infinite',
    [vaultMedia.reducedMotion]: { animation: 'none' },
  },
  errorNotice: {
    ...notice,
    backgroundColor: vault.dangerBg,
    border: `1px solid ${vault.danger}`,
    color: vault.danger,
  },
  warnNotice: {
    ...notice,
    backgroundColor: vault.warnBg,
    border: `1px solid ${vault.warn}`,
    color: vault.warn,
  },

  // ─── Results ───────────────────────────────────────────────────────────────
  resultsHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '6px 12px',
    paddingBottom: '12px',
    marginBottom: '16px',
    borderBottom: `1px solid ${vault.lineStrong}`,
  },
  resultsTitle: {
    margin: 0,
    fontSize: 22,
    fontWeight: 600,
    letterSpacing: '-0.02em',
    color: vault.fg,
  },
  empty: {
    padding: '8px 0',
    fontSize: 15,
    color: vault.muted,
  },
  matchList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  match: {
    padding: '18px 20px',
    borderRadius: vaultRadii.panel,
    backgroundColor: vault.surface,
    border: `1px solid ${vault.line}`,
    [vaultMedia.mobile]: { padding: '16px' },
  },
  matchHead: {
    display: 'flex',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    gap: '6px 10px',
  },
  matchName: {
    margin: 0,
    fontSize: 17,
    fontWeight: 600,
    letterSpacing: '-0.01em',
    color: vault.fg,
  },
  alias: {
    padding: '2px 8px',
    borderRadius: vaultRadii.pill,
    backgroundColor: vault.chip,
    border: `1px solid ${vault.line}`,
    fontFamily: typography.fontFamily.mono,
    fontSize: 11,
    color: vault.muted,
  },
  occurrences: {
    marginLeft: 'auto',
    fontVariantNumeric: 'tabular-nums',
  },
  snippets: {
    margin: '12px 0 0',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  snippet: {
    margin: 0,
    padding: '2px 0 2px 12px',
    borderLeft: `2px solid ${vault.accent}`,
    fontSize: 14,
    lineHeight: 1.55,
    fontStyle: 'italic',
    color: vault.muted,
    overflowWrap: 'anywhere',
  },
  images: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginTop: '14px',
  },
  imageLink: {
    display: 'block',
    padding: '3px',
    borderRadius: '10px',
    background: vaultEffects.slabFrame,
    border: `1px solid ${vault.line}`,
    transition: `border-color ${vaultEffects.transition}, transform ${vaultEffects.transition}`,
    '&:hover': { borderColor: vault.accent, transform: 'translateY(-2px)' },
    [vaultMedia.reducedMotion]: { '&:hover': { transform: 'none' } },
    ...focusRing,
  },
  image: {
    display: 'block',
    width: 64,
    height: 64,
    objectFit: 'cover',
    borderRadius: '7px',
    background: vaultEffects.stripes,
  },
};
